apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: lhdenis35/order-ms:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 9094
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djdk.tls.client.protocols=TLSv1.2"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: orderdb_url
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "orderdb"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices-app
spec:
  selector:
    app: orderapp
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
